### ISSUE TITLE
Update Scraper [DO FIRST]

### ISSUE THREAD

**Issue by CDLlo** [ucsb-cs56-projects/cs56-scrapers-ucsb-curriculum#56]
Currently the method to query the UCSB curriculum for the appropriate page no longer works, likely due to a website update. Update the code such that it can once again query to curriculum. Start in UCSBCurriculumSearch.java and familiarize yourself with the java web libraries used.

Estimate 350 points

**Comment by nathan-inge** [comment]
@CDLlo Justin and I were wondering if it was at all possible for this to be raised to a 500 point issue. Our reason for this increase request are as follows:

 - In addition to working on it during labs, we have gotten together outside of lab and worked for quite a few hours on it. It is quite a big issue considering we are introducing a new parsing library and starting to refactor the way the scraper works. 

- Because of the scope of this issue we have also started to refactor `UCSBCurriculumSearch` . Because of this, we feel that we are also working on part of #53 (which is 200 points).

- Since the website changed, the scraper is completely broken at the moment (and is the reason we are introducing this library refactor), and this has prevented us from working on other issues (and limiting our ability to reach 500 points). 

Thank you for your consideration.

**Comment by CDLlo** [comment]
Given the amount of work you guys are putting into this I would definitely say this issue has become much larger than initially anticipated . Please submit individual issues for each component you mentioned and I will reassess their point values to at least 500 if not more.

**Comment by nathan-inge** [comment]
Justin and I finished up this issue and will create a pull request. As a part of this pull request we addressed issues: 

- #59 
- #60 
- #61 
- #53 

Between the two of us all of these issue took 18 hours. Let me know if you need anything else from us.
